project:
  type: site
  output-dir: docs
  
website:
  title: "GAB2022 Analisis in Situ"
  reader-mode: false
  search: false
  navbar:
    background: "#546e7a"
    foreground: "#ffffff"
    right:
      - icon: github
        href: https://github.com/PPaccioretti/EstadisticaEspacial
        aria-label: GitHub
    left:
      - text: "Slides"
        href: slides.qmd
      - text: "Ejemplo 1"
        href: Ej01_AA.qmd
      - text: "Ejemplo 2"
        href: Ej02_rinde.qmd
  page-footer:
    background: "#546e7a"
    right:
      - text: "&#169; 2022 Pablo Paccioretti, Monica Balzarini, Mariano CÃ³rdoba <span xmlns:cc=\"http://creativecommons.org/ns#\" xmlns:dct=\"http://purl.org/dc/terms/\">licensed under <a href=\"http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1\" target=\"_blank\" rel=\"license noopener noreferrer\" style=\"display:inline-block;\">CC BY 4.0<img style=\"height:18px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1\"><img style=\"height:18px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1\"></a></p>"
      
execute:
  freeze: auto  # re-render only when source changes
  warning: false
  messages: false
  
lang: es
citations-hover: true
knitr:
  opts_chunk: 
    #collapse: true
    comment: "##"
    results: "hold"
format: 
  html:
    theme: [zephyr, theme.scss]
    #self-contained: true
    toc: true
    toc-location: left
    toc-title: Contents
    title-block-categories: false
    df-print: kable
    #monofont: "Roboto Mono"
    #mainfont: "Roboto"
    code-tools: true
    code-link: false
    highlight-style: arrow
    #title-block-banner: "#546e7a"
    #title-block-banner-color: "white"
    code-block-bg: true
    code-block-background: true
    code-block-border-left: true
    fontsize: 13pt
    code-overflow: "scroll"
    #code-overflow: "wrap"
    #code-line-numbers: true

 
